### ISSUE TITLE
Name needs to be adjusted

### ISSUE THREAD

**Issue by haarp** [springlobby/overlay#10]
!!! Section 'Spring' in repos.conf has name different from repository name 'spring' set inside repository

Should be a 10-second affair.

**Comment by abma** [comment]
(untested)

**Comment by haarp** [comment]
Yup, that works, thanks. It's necessary to delete and re-add the overlay tho.

Also, https://springrts.com/wiki/Gentoo_install will have to be updated to make it lowercase :)

**Comment by haarp** [comment]
I took care of the wiki.

**Comment by abma** [comment]
great, thanks! :)
