### ISSUE TITLE
springlobby gentoo ebuild

### ISSUE THREAD

**Issue by serg9** [springlobby/overlay#12]
gentoo overlay, rename it to springlobby-0.243.ebuild please,

needed wx:3.0 to build, didn't thoroughly test it, did eselect wxwidgets to version 3 first, maybe it needs more changes.

[springlobby-0.243.txt](https://github.com/springlobby/overlay/files/171216/springlobby-0.243.txt)

**Comment by abma** [comment]
please create a pull request / add the digest files.

afaik "ebuild digest" needs to be run, too.
