### ISSUE TITLE
Multi-engine installs

### ISSUE THREAD

**Issue by specing** [springlobby/overlay#19]
Would multislotting be accepted? I also took the liberty of

- installing to /opt/spring as the default preefix made no sense with multiple engines.
- Downloading releases via github (possibly more secure+space-saving+no dreaded sourceforge in between).
- upgrading to git-r3 eclass (seemed broken a few weeks ago due to submodule issues)

Current prefixes:
ls /opt/spring/10
100.0/ 102.0/ 103.0/

diff for 100.0: https://paste.pound-python.org/show/XgPHCBliyX69HXXMVnAr/

go? no-go? partially-go?

**Comment by abma** [comment]
imo looks good for me. springlobby doesn't support / search these paths yet afaik but it should be easy to add.

**Comment by specing** [comment]
As per LANANA, it is possible to also use FQDN as provider name (http://www.lanana.org/lsbreg/providers/index.html), thus spring engine builds could go into /opt/springrts.com
Or someone can register a new provider?

I am having some problems with migrating all ebuilds to git as <=103 are broken due to (presumably) Shard repo migration.

**Comment by specing** [comment]
ok, migrating all to git might be a bit unwise.
