### ISSUE TITLE
Missing 'lsl' folder in 105.0 source tarball ?

### ISSUE THREAD

**Issue by mfld-fr** [springlobby/overlay#34]
I am trying to build the spring engine from the 105.0 source tarball: https://springrts.com/dl/buildbot/default/master/105.0/source/spring_105.0_src.tar.gz

The build fails on a missing `lsl` folder:
```
CMake Error at tools/pr-downloader/src/CMakeLists.txt:17 (add_library):
  Cannot find source file:

    lsl/lslutils/platform.cpp
```

I can see that folder on Github for tag 105.0, and the build of a Git clone from that tag succeeds (just after patching for GCC 11 as in the `develop` branch).

Is this .tar.gz tarball correct on the DL server ?

**Comment by abma** [comment]
thanks for reporting!

created a ticket upstream: https://springrts.com/mantis/view.php?id=6446

(yes, it seems its incorrect)

**Comment by mfld-fr** [comment]
Thanks @abma ! Now following the Mantis ticket...
