### ISSUE TITLE
 Bug 831274 - [spring] Ebuild failures occuring in global scope 

### ISSUE THREAD

**Issue by abma** [springlobby/overlay#38]
https://bugs.gentoo.org/831274

**Comment by abma** [comment]
* games-util/pr-downloader-9999: failed sourcing ebuild: inherit requires unknown eclass: games.eclass
* games-util/qtlobby-9999: failed sourcing ebuild: inherit requires unknown eclass: games.eclass

**Comment by mfld-fr** [comment]
@abma : AFAIK, `qtlobby` is not in the first ring of the 'Spring RTS' project (https://springrts.com/wiki/GamesDownloads#Universal_Downloaders), so I propose to drop it out from the overlay.

I also propose `pr-download` `ebuild` for removal, as that facility is included in `springlobby`.

What do you think ?

**Comment by abma** [comment]
yes, please remove them. qtlobby afaik is unmaintained.
pr-downloader is already part of spring and springlobby.

**Comment by mfld-fr** [comment]
@abma : could you please also close https://bugs.gentoo.org/831274 as FIXED ?

**Comment by abma** [comment]
sure!

**Comment by mfld-fr** [comment]
Thanks 👍 !
